config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  # Main resources
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout},
             controllers: {sessions: 'users/sessions'}
  get 'sessions/new'

  # Admin namespace
  namespace :admin do
    resources :feedbacks, only: :index
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  #Common resources
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
    post :gist, on: :member
  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

end

app/models/badge.rb
class Badge < ApplicationRecord
  RULES = { all_tests_in_category?: 'All test in one category',
            on_first_try?: 'Pass the test on first try',
            by_level?: 'Pass all tests with level' }.freeze

  has_many :users, through: :user_badges
  has_many :user_badges

  has_attached_file :image

  validates_attachment :image,
                       content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif'] }

  validates :title, :image, presence: true
end

app/controllers/admin/badges_controller.rb
# frozen_string_literal: true

class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[edit update destroy]

  def new
    @badge = Badge.new
  end

  def create
    badge = Badge.new(badge_params)
    if badge.save
      redirect_to admin_badges_path, notice: 'Badge successfully saved!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path, notice: 'Successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  def index
    @badges = Badge.all
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :description, :image, :rule, :rule_parameter)
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
# frozen_string_literal: true

class BadgesController < ApplicationController
  def index
    @badges = Badge.all
    @user_badges = current_user.badges
  end
end

app/views/admin/badges/_badge.html.slim
tr
  td
    b = badge.title
  td = image_tag(badge.image.url, size: "150x150") if badge.image.exists?
  td = badge.description
  td
    = link_to t('links.edit'), edit_admin_badge_path(badge), class: 'btn btn-primary'
    = link_to t('links.delete'), admin_badge_path(badge), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"

app/views/admin/badges/_form.html.slim
= render 'shared/errors', resource: @badge
div class="row "
  div class="col col-md-4 mx-auto"
    h3 class="text-center mt-3"
    = form_with model: [:admin, @badge], local:true do |form|
      div class="form-group"
        = form.label :title
        = form.text_field  :title, class: 'form-control'
      div class="form-group"
        = form.label :description
        = form.text_area :description, class: 'form-control'
      div class="form-group"
        = form.label :image
        = form.file_field :image, class: 'form-control-file'
      div class="form-group"
        = form.label :rule
        = form.select(:rule, Badge::RULES.invert,  {:prompt => "Select Rule"}, {:class => 'form-control'} )
        = form.collection_select(:rule_parameter, Category.all, :id, :title, {}, {id: 'category', class:'form-control hide'})
        = form.select(:rule_parameter, (1..15).to_a, {}, {id: 'level', class:'form-control hide'})
      div class="form-group"
        = form.submit
      div class="form-group"
        = link_to "Cancel", admin_badges_path, class: 'btn btn-primary'

app/views/admin/badges/edit.html.slim
h2.text-center = t('.header')
= render 'form'

app/views/admin/badges/index.html.slim
= link_to t('links.badges.new_badge'), new_admin_badge_path, class: 'btn btn-primary'

div class="row"
  div class="col mt-4"
    h1 = t('.header')
    table class="table table-hover"
      tr
        th class="sort-by-title pointer"
          = t('.t_title')
          = octicon 'arrow-up', class: 'text-success hide'
          = octicon 'arrow-down', class: 'text-success hide'
        th #{t('.t_image')}
        th #{t('.t_decription')}
        th #{t('.t_actions')}
      - if @badges.present?
        = render @badges
      - else
        p No one

app/views/admin/badges/new.html.slim
h2.text-center = t('.header')
= render 'form'