config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  # Main resources
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout},
             controllers: {sessions: 'users/sessions'}
  get 'sessions/new'

  # Admin namespace
  namespace :admin do
    resources :feedbacks, only: :index
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  #Common resources
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
    post :gist, on: :member
  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
  validates :firstname, presence: true
  validates :lastname, presence: true
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  # validate :validate_answers_count, on: :create

  def validate_answers_count
    errors.add(:question, 'Only from 1 to 4 answers allowed') if question.answers.count >= 4
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  RULES = { all_tests_in_category?: 'All test in one category',
            on_first_try?: 'Pass the test on first try',
            by_level?: 'Pass all tests with level' }.freeze

  has_many :users, through: :user_badges
  has_many :user_badges

  has_attached_file :image

  validates_attachment :image,
                       content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif'] }

  validates :title, :image, presence: true
end

app/models/categorization.rb
# frozen_string_literal: true

class Categorization < ApplicationRecord
  belongs_to :test
  belongs_to :category
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  default_scope { order(:title) }
  scope :with_name, ->(title) { where(title: title) }

  has_many :categorizations
  has_many :tests, through: :categorizations

  validates :title, presence: true,
                    uniqueness: true
end

app/models/feedback.rb
# frozen_string_literal: true

class Feedback < ApplicationRecord
  belongs_to :user, optional: true
  validates :email, :body, presence: true
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  has_many :test_passages
  has_many :users, through: :test_passages
  has_many :categorizations
  has_many :categories, through: :categorizations
  has_many :questions, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  scope :easy,   -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard,   -> { where(level: 5..Float::INFINITY) }
  scope :with_level,  ->(level) { where(level: level) }
  scope :by_category, ->(category) { joins(:category).where(categories: { title: category }).order(title: :desc) }

  validates :title, presence: true,
                    uniqueness: { scope: :level, message: 'Should be  only one title-level' }
  validates :level, numericality: { only_integer: true, greater_than: 0 }

  def self.get_titles(category_name)
    by_category(category_name).pluck(:title)
  end
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', foreign_key: 'current_question_id', optional: true

  before_validation :before_validation_set_questions

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def time_left
    end_time = created_at + (test.timer * 60)
    end_time - Time.current
  end

  def time_over?
    time_left < 0
  end

  def time_end
    (created_at + (test.timer * 60)) if test.timer.present?
  end

  def success?
    count_percent_correct > 85
  end

  def count_percent_correct
    (correct_questions * 100) / number_of_questions
  end

  def current_question_number
    number_of_questions - collect_questions.count
  end

  def number_of_questions
    test.questions.count
  end

  def next_question
    collect_questions.first
  end

  def completed
    self.current_question = nil
  end
  private

  def before_validation_set_questions
    if new_record?
      self.current_question = test.questions.first if test.present?
    else
      self.current_question = next_question
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids&.map(&:to_i)&.sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def collect_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :authored_tests, class_name: 'Test', foreign_key: :author_id
  has_many :gists
  has_many :feedbacks
  has_many :user_badges
  has_many :badges, through: :user_badges

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  def admin?
    is_a?(Admin)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def show_tests_with_level(level_value)
    tests.with_level(level_value)
  end

  def fullname
    firstname + ' ' + lastname
  end

  def completed_tests
    test_passages.select(&:completed?)
  end
end

app/models/user_badge.rb
# frozen_string_literal: true

class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/tests_controller.rb
# frozen_string_literal: true

class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  AUTHOR = 'Stanislav Karpinsky'
  def current_year
    Time.current.year
  end

  def github_url(author = AUTHOR, repo)
    link_to author, repo
  end

  def alert_body
    content_tag :p, flash[:alert], class: 'flash alert'
  end

  def flash_messages
    html = ''
    flash.each { |key, value| html << content_tag(:p, value, class: "flash #{key}") }
    html.html_safe
  end
end

app/helpers/feedbacks_helper.rb
# frozen_string_literal: true

module FeedbacksHelper
  def feedback_author_name(feedback)
    feedback.user&.fullname || 'Anonymous'
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(resource)
    if @question.new_record?
      "Create NEW | Test: #{resource.title}| question"
    else
      "Edit |Test: #{resource.title}| question"
    end
  end
end

app/helpers/test_passages_helper.rb
# frozen_string_literal: true

module TestPassagesHelper
  def count_progress_percent(test_passage)
    test_passage.current_question_number * 100 / test_passage.test.questions.count
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 0 => "Very easy", 1 => "Easy",
                  2 => "Medium", 3 => "Hard",
                  4 => "Very hard", 5 => "For Heroes" }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :uncountable
  end
end

app/views/admin/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
  => link_to 'Test Guru', root_path, class: 'navbar-brand'
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon

  .collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item.active
        =< link_to t('links.navbar.panel'), admin_tests_path, class: 'nav-link'
      li.nav-item.active
        =<> link_to t('links.navbar.gists'), admin_gists_path, class: 'nav-link'
      li.nav-item.active
        =<> link_to t('links.navbar.tests'), tests_path, class: 'nav-link'
      li.nav-item.active
        =<> link_to t('links.navbar.feedbacks'), admin_feedbacks_path, class: 'nav-link'
      li.nav-item.active
        =<> link_to t('links.navbar.badges'), admin_badges_path, class: 'nav-link'
      li.nav-item.active
        =<> link_to t('links.navbar.logout'), destroy_user_session_path, method: :delete, class: 'nav-link'
      li.nav-item.active
        = link_to t('links.navbar.contact'), new_feedback_path, class: 'nav-link'
    ul.navbar-nav
      li.nav-item
        => link_to 'English', url_for(lang: :en), class: 'btn nav-link'
      li.nav-item
        =< link_to 'Русский', url_for(lang: :ru), class: 'btn nav-link'
div class="row"
  div class="col"
    div class="greeting"
      - if user_signed_in?
        ' Добро пожаловать,
        b => current_user.firstname

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdminPanel | TestGuru</title>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render "admin/nav" %>
<div class="container">
  <%= render "shared/flash" %>
  <%= yield %>
</div>
</body>
<% if Rails.env.development? %>
<%= console %>
<% end %>
<%= render "shared/footer" %>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= render "shared/flash" %>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>

  </body>


</html>

app/views/shared/_errors.html.slim
-if resource.present? && resource.errors.any?
  = content_tag :div, class: 'resource-errors', data: { resource_id: resource.id} do
    = t('.header', count: resource.errors.count)
    - resource.errors.full_messages.each do |message|
      div class="alert alert-danger" = message

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  = content_tag :div, message, class: "alert alert-#{key}"

app/views/shared/_footer.html.slim
footer class="footer mt-4"
  .text-center
    .row.justify-content-center
      .col.mt-4
        p
          = github_url("TEST GURU", "https://github.com/wildkain/TestGuru")
        p
          = link_to t('links.footer-thinknetica'), 'http://thinknetica.com/', target: :_blank
        p
          | Copyright &copy; #{current_year} #{ApplicationHelper::AUTHOR}

app/views/shared/_navbar.html.slim
.container-fluid.navbar-menu
  nav.navbar.navbar-expand-lg.navbar-light.bg-light
    => link_to 'Test Guru', root_path, class: 'navbar-brand'
    button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon

    .collapse.navbar-collapse#navbarText
      ul.navbar-nav.mr-auto
        - if user_signed_in?
          li.nav-item
            = link_to t('links.navbar.badges'), badges_path, class: 'nav-link'
          - if current_user.admin?
            li.nav-item
              =< link_to t('links.navbar.panel'), admin_tests_path, class: 'nav-link'
          li.nav-item
            =< link_to t('links.navbar.logout'), destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item
            => link_to t('links.navbar.login'), new_user_session_path, class: 'nav-link'
          li.nav-item
            =< link_to t('links.navbar.signup'), new_user_registration_path, class: 'nav-link'
        li.nav-item
          = link_to t('links.navbar.contact'), new_feedback_path, class: 'btn'
          = octicon "comment"
      ul.navbar-nav
        li.nav-item
          => link_to 'English', url_for(lang: :en), class: 'btn'
        li.nav-item
          =< link_to 'Русский', url_for(lang: :ru), class: 'btn'
  .container-fluid
    div class="row"
      div class="col"
        div class="greeting mt-2"
          - if user_signed_in?
            ' Добро пожаловать,
            b => current_user.firstname