config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  # Main resources
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout},
             controllers: {sessions: 'users/sessions'}
  get 'sessions/new'

  # Admin namespace
  namespace :admin do
    resources :feedbacks, only: :index
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  #Common resources
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
    post :gist, on: :member
  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/controllers/admin/gists_controller.rb
# frozen_string_literal: true

class Admin::GistsController < Admin::BaseController
  def index
    @gists = Gist.all
  end
end

app/views/admin/gists/_gist.html.slim
tr
  td =  link_to truncate(gist.question.body, length: 25), admin_question_path(gist.question)
  td = link_to 'View on Gists.github', gist.path, target:'_blank', class: 'btn btn-primary'
  td = gist.user.firstname

app/views/admin/gists/index.html.slim
div class="row"
  div class="col"
    - if @gists.present?
      h1 Created Gists
      table class="table table-hover"
        tr
          th Question
          th URL
          th User
        = render @gists

    - else
      p No one
    hr
    = link_to 'Back', admin_tests_path, class: 'btn btn-primary'