config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  # Main resources
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout},
             controllers: {sessions: 'users/sessions'}
  get 'sessions/new'

  # Admin namespace
  namespace :admin do
    resources :feedbacks, only: :index
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  #Common resources
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
    post :gist, on: :member
  end

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', foreign_key: 'current_question_id', optional: true

  before_validation :before_validation_set_questions

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def time_left
    end_time = created_at + (test.timer * 60)
    end_time - Time.current
  end

  def time_over?
    time_left < 0
  end

  def time_end
    (created_at + (test.timer * 60)) if test.timer.present?
  end

  def success?
    count_percent_correct > 85
  end

  def count_percent_correct
    (correct_questions * 100) / number_of_questions
  end

  def current_question_number
    number_of_questions - collect_questions.count
  end

  def number_of_questions
    test.questions.count
  end

  def next_question
    collect_questions.first
  end

  def completed
    self.current_question = nil
  end
  private

  def before_validation_set_questions
    if new_record?
      self.current_question = test.questions.first if test.present?
    else
      self.current_question = next_question
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids&.map(&:to_i)&.sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def collect_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :find_test_passage, only: %i[show result update gist]
  before_action :authenticate_user!

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])
    @test_passage.completed if @test_passage.time_over?

    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      badge_service = BadgeDistributorService.new(@test_passage)
      @test_passage.user.badges << badge_service.assign_badges
      flash[:notice] = 'You recieve a Badge' if badge_service.badge_given?
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    result = GistQuestionService.new(@test_passage.current_question).call
    if successed?(result)
      current_user.gists.create(question_id: @test_passage.current_question_id, path: result.html_url)
      flash[:notice] = t('.success', gist_url: view_context.link_to('Gist', result.html_url, target: '_blank'))
    else
      flash[:alert] = t('.failure')
    end

    redirect_to @test_passage
  end

  def successed?(result)
    result.created_at.present?
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
# frozen_string_literal: true

module TestPassagesHelper
  def count_progress_percent(test_passage)
    test_passage.current_question_number * 100 / test_passage.test.questions.count
  end
end

app/views/test_passages/result.html.slim
div class="row justify-content-center mt-3"
  div class="col col-md-4"
    div class="card bg-default"
      div class="card-header text-center bg-light"
        h5  #{t('.header', title: @test_passage.test.title)}
      div class="card-body"
        h3 #{t('.info')}
        li #{t('.all_q')}: #{@test_passage.number_of_questions}
        li #{t('.correct')}: #{@test_passage.correct_questions}
        li #{t('.rate')}: #{@test_passage.count_percent_correct} %

      div class="card-footer"
        div class="test-result"
          - if @test_passage.success?
            div class="result-success"
              = image_tag("success.png", size:"150x100")
          - else
            div class="result-fail"
              = image_tag("fail.png", size:"150x100")




div class = "nav"
  = link_to 'Back to Tests', tests_path, class: 'btn btn-primary'

app/views/test_passages/show.html.slim
div class="row justify-content-center mt-4"
  div class="col col-md-8"
    div class="card bg-default"
      h2 class="card-header" = t('.header', title: @test_passage.test.title)

      div class="progress mt-2 ml-2 mr-2"
        = content_tag :div, '',class: 'progress-bar test-progress-bar', data: { test_progress: count_progress_percent(@test_passage) }
      div class="card-body"
        p class="card-text"
          li #{t('.counter')} : #{@test_passage.current_question_number} \ #{@test_passage.number_of_questions}

        p class="card-text"
          h3 = @test_passage.current_question.body


        = form_with url: test_passage_path(@test_passage), local: true, method: :put do |form|
          = form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false  do |b|
            div class="form-group"
              = b.check_box id: "answer_ids_#{b.object.id}"
              = b.label
          .form-group
            = form.submit
      div class="card-footer"
        .form-group
          = link_to t('links.create_gist'), gist_test_passage_path(@test_passage), method: :post

  .col.col-md-2
    =content_tag :div, '', class: 'field alert', id: 'timer', data: { timer_count: @test_passage.time_end.to_i }
      = content_tag :span
      = content_tag :span